// <auto-generated />
using System;
using BillApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BillApp.Migrations
{
    [DbContext(typeof(FeeItemContext))]
    [Migration("20190204170126_InitialCreateFeeItem")]
    partial class InitialCreateFeeItem
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028");

            modelBuilder.Entity("BillApp.Models.FeeItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Code");

                    b.Property<string>("Notes");

                    b.Property<DateTime>("TransactionDate");

                    b.HasKey("Id");

                    b.ToTable("FeeItem");
                });
#pragma warning restore 612, 618
        }
    }
}
